name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt pytest requests

    - name: Run tests
      run: |
        python -m flask run &  # lancer Flask en arrière-plan
        sleep 5
        pytest tests/

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/flask_api:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/flask_api:latest

    - name: Terraform Init & Apply
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
